FROM python:2

RUN apt-get update && apt-get install -y --no-install-recommends postgresql-client

WORKDIR /opt/
RUN git clone https://github.com/lorawan-sk/lorawan-sk-backend.git

WORKDIR /opt/lorawan-sk-backend/web_api/
RUN pip install -r requirements.txt
