# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_node_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(default=b'', max_length=128),
        ),
    ]
