# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_node_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='responsible',
            field=models.CharField(default='unknown', max_length=128),
            preserve_default=False,
        ),
    ]
