# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_node_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.TextField(),
        ),
    ]
