# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_node_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='location',
            field=models.CharField(default=b'', max_length=512),
        ),
    ]
