# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_gateway_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=b'?', max_length=256)),
                ('numeric', models.IntegerField()),
            ],
        ),
    ]
