# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_keys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keys',
            new_name='Key',
        ),
    ]
