# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160204_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='unit',
            field=models.CharField(default=b'?', max_length=256),
        ),
    ]
