# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20160217_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='gps_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='node',
            name='gps_lon',
            field=models.FloatField(default=0.0),
        ),
    ]
