# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20160217_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={},
        ),
    ]
