# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20160219_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='node',
            field=models.ForeignKey(db_column=b'serial', default='', on_delete=django.db.models.deletion.CASCADE, to='api.Node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='rssi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='key',
            field=models.ForeignKey(db_column=b'_key', on_delete=django.db.models.deletion.CASCADE, to='api.Key'),
        ),
    ]
