# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20160219_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='gw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Gateway'),
        ),
    ]
