# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_point_gw'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='raw_packet',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gateway',
            name='gps_lat',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='gps_lon',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='location',
            field=models.CharField(blank=True, default=b'', max_length=512),
        ),
    ]
