# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20160301_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='serial',
            field=models.CharField(blank=True, default=b'', max_length=128),
        ),
        migrations.AlterField(
            model_name='point',
            name='key',
            field=models.ForeignKey(db_column=b'_key', db_constraint=False, default='', on_delete=django.db.models.deletion.CASCADE, to='api.Key'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='node',
            field=models.ForeignKey(db_column=b'serial', db_constraint=False, default='', on_delete=django.db.models.deletion.CASCADE, to='api.Node'),
            preserve_default=False,
        ),
    ]
