# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20160705_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawpoint',
            options={},
        ),
    ]
