# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20160705_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpoint',
            name='gw',
            field=models.ForeignKey(db_column=b'gw_serial', default='', on_delete=django.db.models.deletion.CASCADE, to='api.Gateway'),
            preserve_default=False,
        ),
    ]
