# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rawpoint_gw'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpoint',
            name='node',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Node'),
            preserve_default=False,
        ),
    ]
