# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20160705_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_id',
            field=models.IntegerField(null=True),
        ),
    ]
