# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_node_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
