# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20160815_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
