# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20160815_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawpoint',
            name='gw',
            field=models.ForeignKey(db_column=b'gw_serial', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Gateway'),
        ),
    ]
