# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20160815_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpoint',
            name='snr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawpoint',
            name='rssi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
