# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20160815_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpoint',
            name='gateway_serial',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
