# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rawpoint_gateway_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_hash',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
