# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_node_node_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='node_hash',
            new_name='api_key',
        ),
    ]
