# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20160828_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='nodetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.NodeType'),
        ),
    ]
