# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20160828_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='last_rawpoint',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
