# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_node_last_rawpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpoint',
            name='state',
            field=models.IntegerField(choices=[(0, b'new'), (1, b'processed'), (2, b'failed to process')], default=0),
        ),
    ]
