# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rawpoint_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawpoint',
            name='gw',
            field=models.ForeignKey(blank=True, db_column=b'gw_serial', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Gateway'),
        ),
    ]
