# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20160901_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='gw',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Gateway'),
        ),
        migrations.AlterField(
            model_name='point',
            name='key',
            field=models.ForeignKey(blank=True, db_column=b'_key', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Key'),
        ),
        migrations.AlterField(
            model_name='point',
            name='node',
            field=models.ForeignKey(blank=True, db_column=b'serial', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Node'),
        ),
        migrations.AlterField(
            model_name='point',
            name='raw_packet',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='rawpoint',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Rawpoint'),
        ),
        migrations.AlterField(
            model_name='point',
            name='rssi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
