# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_point_seq_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='seq_number',
        ),
        migrations.AddField(
            model_name='rawpoint',
            name='seq_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
