# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20160912_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoRaWANRawPoint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phy_payload', models.CharField(max_length=1024)),
                ('gateway_serial', models.CharField(blank=True, max_length=128, null=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('lsnr', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
