# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_lorawanrawpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorawanrawpoint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
