# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20161004_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorawanrawpoint',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
