# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20161004_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lorawanrawpoint',
            old_name='phy_payload',
            new_name='phypayload',
        ),
    ]
