# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20161004_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lorawanrawpoint',
            old_name='phypayload',
            new_name='rawpayload',
        ),
    ]
