# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20161004_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorawanrawpoint',
            name='rawpayload',
            field=models.TextField(),
        ),
    ]
