# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20161004_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lorawanrawpoint',
            name='rawpayload',
        ),
        migrations.AddField(
            model_name='lorawanrawpoint',
            name='chan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lorawanrawpoint',
            name='codr',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='lorawanrawpoint',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lorawanrawpoint',
            name='datr',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='lorawanrawpoint',
            name='freq',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lorawanrawpoint',
            name='lsnr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
