# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20161004_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lorawanrawpoint',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.AddField(
            model_name='lorawanrawpoint',
            name='tmst',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
