# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20161004_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorawanrawpoint',
            name='DevAddr',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='lorawanrawpoint',
            name='FRMPayload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
