# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_lorawanrawpoint_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoRaApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('AppEUI', models.CharField(max_length=128)),
                ('api_key', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
