# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_loraapplication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoRaApplication',
            new_name='LoRaWANApplication',
        ),
    ]
