# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20161005_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='lorawan_DevAddr',
        ),
    ]
