# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_remove_node_lorawan_devaddr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='lorawan_ASK',
            new_name='lorawan_AppSKey',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='lorawan_NSK',
            new_name='lorawan_NwkSKey',
        ),
    ]
