# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20161005_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorawanrawpoint',
            name='FCnt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
