# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_lorawanrawpoint_fcnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorawanrawpoint',
            name='MIC',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
