# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_lorawanrawpoint_mtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorawanrawpoint',
            name='FPort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
