# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_lorawanrawpoint_fport'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorawanrawpoint',
            name='FCtrl',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lorawanrawpoint',
            name='FOpts',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
