# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20161006_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lorawanrawpoint',
            old_name='FCnt',
            new_name='FCntDown',
        ),
        migrations.AddField(
            model_name='lorawanrawpoint',
            name='FCntUp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
