# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20161006_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lorawanrawpoint',
            old_name='FCntDown',
            new_name='FCnt',
        ),
        migrations.RemoveField(
            model_name='lorawanrawpoint',
            name='FCntUp',
        ),
        migrations.AddField(
            model_name='node',
            name='lorawan_FCntDown',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='lorawan_FCntUp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
