# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20161006_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='lorawan_FCntDown',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='lorawan_FCntUp',
            field=models.IntegerField(default=0),
        ),
    ]
