# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20161006_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='lorawan_band',
            field=models.IntegerField(blank=True, choices=[(0, b'EU863-870'), (1, b'US902-928'), (2, b'CN779-787'), (3, b'EU433')], null=True),
        ),
    ]
