# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20161006_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorawanrawpoint',
            name='data',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
