# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20161006_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='mac',
            field=models.CharField(blank=True, default=b'', max_length=12),
        ),
    ]
