# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 14:26
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_gateway_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorawanapplication',
            name='api_key',
            field=models.CharField(blank=True, default=api.models.generate_api_key, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='api_key',
            field=models.CharField(default=api.models.generate_api_key, max_length=256),
        ),
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userext',
            name='user_api_key',
            field=models.CharField(blank=True, default=api.models.generate_api_key, max_length=256, null=True),
        ),
    ]
