# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 14:28
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20161130_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userext',
            name='user_api_key',
            field=models.CharField(default=api.models.generate_api_key, max_length=256),
        ),
    ]
