# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20161130_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='userext',
            name='user_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
