# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_userext_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userext',
            old_name='user_phone',
            new_name='phone',
        ),
    ]
