# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20161202_1849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExt',
            new_name='Profile',
        ),
    ]
