# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 22:26
from __future__ import unicode_literals

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20161202_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='api_key',
            field=models.CharField(default=api.models.generate_api_key, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='location',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+12345678'. With 8 to 15 digits.", regex=b'^\\+\\d{8,15}$')]),
        ),
    ]
