# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-04 14:55
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_gateway_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='mac',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='serial',
            field=models.CharField(blank=True, default=api.models.generate_api_key, max_length=128),
        ),
    ]
