# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-08 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0093_auto_20161204_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='admins',
            field=models.ManyToManyField(blank=True, null=True, related_name='_node_admins_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
