# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-08 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_node_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='_node_admins_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
