# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_auto_20161208_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='lorawan_AppSKey',
        ),
        migrations.RemoveField(
            model_name='node',
            name='lorawan_FCntDown',
        ),
        migrations.RemoveField(
            model_name='node',
            name='lorawan_FCntUp',
        ),
        migrations.RemoveField(
            model_name='node',
            name='lorawan_NwkSKey',
        ),
        migrations.AddField(
            model_name='lorawanapplication',
            name='AppKey',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
