# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20161227_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='lorawan_DevEUI',
        ),
    ]
