# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_remove_node_lorawan_deveui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorawanapplication',
            name='AppKey',
            field=models.CharField(max_length=128),
        ),
    ]
