# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_auto_20161227_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='mac',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
