# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_auto_20170111_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='last_seen_ip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
