# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-22 09:20
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_auto_20170121_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='mqtt_password',
            field=models.CharField(blank=True, default=api.models.generate_mqtt_password, max_length=16, null=True),
        ),
    ]
