# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_gateway_mqtt_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DevAddr', models.CharField(blank=True, max_length=8, null=True)),
                ('NwkSKey', models.CharField(blank=True, max_length=32, null=True)),
                ('AppSKey', models.CharField(blank=True, max_length=32, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Node')),
            ],
        ),
    ]
