# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_auto_20170312_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='value',
            field=models.FloatField(),
        ),
    ]
