# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_auto_20170312_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='snr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='rssi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
