# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_auto_20170312_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='mac',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
