# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_auto_20170312_2059'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='point',
            unique_together=set([('key', 'node', 'value', 'timestamp', 'gw')]),
        ),
    ]
